// Front-End-Web-Development-with-React/Assignment Zips/Assignment 2/AboutComponent.js
import React from "react";
import {
  Breadcrumb,
  BreadcrumbItem,
  Card,
  CardBody,
  CardHeader,
  Media,
} from "reactstrap";
import { Link } from "react-router-dom";

const RenderLeader = ({ leader }) => {
  return (
    <Media tag="li">
      <Media left>
        <Media object src="assets/images/alberto.png" alt={leader.name} />
      </Media>
      <Media body className="ml-5">
        <Media heading>{leader.name}</Media>
        <p>{leader.designation}</p>
        <p>{leader.description}</p>
      </Media>
    </Media>
  );
};

const About = ({ leaders: Leaders }) => {
  const leaders = Leaders.map((leader) => {
    return <RenderLeader leader={leader} />;
  });

  return (
    <div className="container">
      <div className="row">
        <Breadcrumb>
          <BreadcrumbItem>
            <Link to="/home">Home</Link>
          </BreadcrumbItem>
          <BreadcrumbItem active>About Us</BreadcrumbItem>
        </Breadcrumb>
        <div className="col-12">
          <h3>About Us</h3>
          <hr />
        </div>
      </div>
      <div className="row row-content">
        <div className="col-12 col-md-6">
          <h2>Our History</h2>
          <p>
            Started in 2010, Ristorante con Fusion quickly established itself as
            a culinary icon par excellence in Hong Kong. With its unique brand
            of world fusion cuisine that can be found nowhere else, it enjoys
            patronage from the A-list clientele in Hong Kong. Featuring four of
            the best three-star Michelin chefs in the world, you never know what
            will arrive on your plate the next time you visit us.
          </p>
          <p>
            The restaurant traces its humble beginnings to{" "}
            <em>The Frying Pan</em>, a successful chain started by our CEO, Mr.
            Peter Pan, that featured for the first time the world's best
            cuisines in a pan.
          </p>
        </div>
        <div className="col-12 col-md-5">
          <Card>
            <CardHeader className="bg-primary text-white">
              Facts At a Glance
            </CardHeader>
            <CardBody>
              <dl className="row p-1">
                <dt className="col-6">Started</dt>
                <dd className="col-6">3 Feb. 2013</dd>
                <dt className="col-6">Major Stake Holder</dt>
                <dd className="col-6">HK Fine Foods Inc.</dd>
                <dt className="col-6">Last Year's Turnover</dt>
                <dd className="col-6">$1,250,375</dd>
                <dt className="col-6">Employees</dt>
                <dd className="col-6">40</dd>
              </dl>
            </CardBody>
          </Card>
        </div>
        <div className="col-12">
          <Card>
            <CardBody className="bg-faded">
              <blockquote className="blockquote">
                <p className="mb-0">
                  You better cut the pizza in four pieces because I'm not hungry
                  enough to eat six.
                </p>
                <footer className="blockquote-footer">
                  Yogi Berra,
                  <cite title="Source Title">
                    The Wit and Wisdom of Yogi Berra, P. Pepe, Diversion Books,
                    2014
                  </cite>
                </footer>
              </blockquote>
            </CardBody>
          </Card>
        </div>
      </div>
      <div className="row row-content">
        <div className="col-12">
          <h2>Corporate Leadership</h2>
        </div>
        <div className="col-12">
          <Media list>{leaders}</Media>
        </div>
      </div>
    </div>
  );
};

export default About;

// Angular/confusion/src/app/about/about.component.ts
import { Component, OnInit } from '@angular/core';
import { LeaderService } from '../services/leader.service';
import { Leader } from '../shared/leader';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css'],
})
export class AboutComponent implements OnInit {
  constructor(private leaderService: LeaderService) {}
  leaders: Leader[] | undefined;
  ngOnInit(): void {
    this.leaders = this.leaderService.getAllLeaders();
  }
}

<div class="container" fxLayout="column" fxLayoutGap="10px">
  <div fxFlex>
    <div>
      <h3>About Us</h3>
      <hr />
    </div>
  </div>

  <div fxFlex>
    <div fxLayout="column" fxLayout.gt-sm="row">
      <div fxFlex="70">
        <h2>Our History</h2>
        <p>
          Started in 2010, Ristorante con Fusion quickly established itself as a
          culinary icon par excellence in Hong Kong. With its unique brand of
          world fusion cuisine that can be found nowhere else, it enjoys
          patronage from the A-list clientele in Hong Kong. Featuring four of
          the best three-star Michelin chefs in the world, you never know what
          will arrive on your plate the next time you visit us.
        </p>
        <p>
          The restaurant traces its humble beginnings to
          <em>The Frying Pan</em>, a successful chain started by our CEO, Mr.
          Peter Pan, that featured for the first time the world's best cuisines
          in a pan.
        </p>
      </div>
      <div fxFlex="30">
        <mat-card>
          <mat-card-header>
            <mat-card-title>
              <h2>Facts At a Glance</h2>
            </mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <dl>
              <dt>Started</dt>
              <dd>3 Feb. 2013</dd>
              <dt>Major Stake Holder</dt>
              <dd>HK Fine Foods Inc.</dd>
              <dt>Last Year's Turnover</dt>
              <dd>$1,250,375</dd>
              <dt>Employees</dt>
              <dd>40</dd>
            </dl>
          </mat-card-content>
        </mat-card>
      </div>
    </div>
  </div>

  <div fxFlex>
    <mat-card>
      <blockquote>
        <h3>
          You better cut the pizza in four pieces because I'm not hungry enough
          to eat six.
        </h3>
        <footer>
          -- Yogi Berra,
          <cite
            >The Wit and Wisdom of Yogi Berra, P. Pepe, Diversion Books,
            2014</cite
          >
        </footer>
      </blockquote>
    </mat-card>
  </div>

  <div fxFlex>
    <h2>Corporate Leadership</h2>
    <mat-list *ngIf="leaders">
      <mat-list-item
        style="height: max-content; padding: 10px 0px"
        *ngFor="let leader of leaders"
      >
        <img
          matListItemAvatar
          src="{{ leader.image }}"
          alt="{{ leader.name }}"
        />
        <h5
          mat-line
          style="
            margin: 0;
            font-size: 12h4x;
            line-height: 15px;
            font-weight: 400;
          "
        >
          {{ leader.name }} {{ leader.abbr }}
        </h5>
        <p mat-line style="margin: 0; font-size: 12px; line-height: 15px">
          {{ leader.designation }}
        </p>

        <p
          style="
            margin: 0;
            font-size: 12px;
            line-height: 15px;
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
          "
        >
          {{ leader.description }}
        </p>
      </mat-list-item>
    </mat-list>
    <div [hidden]="leaders">
      <mat-spinner></mat-spinner>
      <h4>Loading . . . Please Wait</h4>
    </div>
  </div>
</div>
