// Front-End-Web-Development-with-React/Exercises/confusion/src/components/FooterComponent.js
import React from "react";
import { Link } from "react-router-dom";

const Footer = () => {
  return (
    <div className="footer">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-4 offset-1 col-sm-2">
            <h5>Links</h5>
            <ul className="list-unstyled">
              <li>
                <Link to="/home">Home</Link>
              </li>
              <li>
                <Link to="/aboutus">About</Link>
              </li>
              <li>
                <Link to="/menu">Menu</Link>
              </li>
              <li>
                <Link to="/contactus">Contact</Link>
              </li>
            </ul>
          </div>
          <div className="col-7 col-sm-5">
            <h5>Our Address</h5>
            <address>
              121, Clear Water Bay Road
              <br />
              Clear Water Bay, Kowloon
              <br />
              HONG KONG
              <br />
              <i className="fa fa-phone fa-lg"></i>: +852 1234 5678
              <br />
              <i className="fa fa-fax fa-lg"></i>: +852 8765 4321
              <br />
              <i className="fa fa-envelope fa-lg"></i>:{" "}
              <a href="mailto:confusion@food.net">confusion@food.net</a>
            </address>
          </div>
          <div className="col-12 col-sm-4 align-self-center">
            <div className="text-center">
              <a
                className="btn btn-social-icon btn-google"
                href="http://google.com/+"
              >
                <i className="fa fa-google-plus"></i>
              </a>
              <a
                className="btn btn-social-icon btn-facebook"
                href="http://www.facebook.com/profile.php?id="
              >
                <i className="fa fa-facebook"></i>
              </a>
              <a
                className="btn btn-social-icon btn-linkedin"
                href="http://www.linkedin.com/in/"
              >
                <i className="fa fa-linkedin"></i>
              </a>
              <a
                className="btn btn-social-icon btn-twitter"
                href="http://twitter.com/"
              >
                <i className="fa fa-twitter"></i>
              </a>
              <a
                className="btn btn-social-icon btn-google"
                href="http://youtube.com/"
              >
                <i className="fa fa-youtube"></i>
              </a>
              <a className="btn btn-social-icon" href="mailto:">
                <i className="fa fa-envelope-o"></i>
              </a>
            </div>
          </div>
        </div>
        <div className="row justify-content-center">
          <div className="col-auto">
            <p>© Copyright 2018 Ristorante Con Fusion</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Footer;

// Angular/confusion/src/app/footer/footer.component.ts
import { Component } from '@angular/core';
import { faBookmark } from '@fortawesome/free-regular-svg-icons';

import {} from '@fortawesome/fontawesome-svg-core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent {
  faCoffee = faBookmark;
}

<div
  class="container footer"
  fxLayout="row wrap"
  fxLayout.lt-md="column"
  fxLayoutAlign="center center"
  fxLayoutGap="10px"
>
  <div fxFlex="100" fxFlex.gt-sm="50">
    <div fxLayout="row">
      <div fxFlex="40" fxFlexOffset="20px">
        <h4>Links</h4>
        <mat-list>
          <mat-list-item class="footer-nav-button"
            ><a mat-button>Home</a></mat-list-item
          >
          <mat-list-item class="footer-nav-button"
            ><a mat-button>About</a></mat-list-item
          >
          <mat-list-item class="footer-nav-button"
            ><a mat-button>Menu</a></mat-list-item
          >
          <mat-list-item class="footer-nav-button"
            ><a mat-button>Contact</a></mat-list-item
          >
        </mat-list>
      </div>
      <div fxFlex="55">
        <h4>Our Address</h4>
        <address style="text-size: 80%">
          121, Clear Water Bay Road<br />
          Clear Water Bay, Kowloon<br />
          HONG KONG<br />
          <fa-icon [icon]="faCoffee"></fa-icon>: +852 1234 5678<br />
          <fa-icon [icon]="faCoffee"></fa-icon>: +852 8765 4321<br />
          <fa-icon [icon]="faCoffee"></fa-icon>:
          <a href="mailto:confusion@food.net">confusion@food.net</a>
        </address>
      </div>
    </div>
  </div>
  <div fxFlex="100" fxFlex.gt-sm="45">
    <div style="text-align: center">
      <a mat-icon-button class="btn-google-plus" href="http://google.com/+"
        ><fa-icon [icon]="faCoffee"></fa-icon
      ></a>
      <a
        mat-icon-button
        class="btn-facebook"
        href="http://www.facebook.com/profile.php?id="
        ><fa-icon [icon]="faCoffee"></fa-icon
      ></a>
      <a mat-icon-button class="btn-linkedin" href="http://www.linkedin.com/in/"
        ><fa-icon [icon]="faCoffee"></fa-icon
      ></a>
      <a mat-icon-button class="btn-twitter" href="http://twitter.com/"
        ><fa-icon [icon]="faCoffee"></fa-icon
      ></a>
      <a mat-icon-button class="btn-youtube" href="http://youtube.com/"
        ><fa-icon [icon]="faCoffee"></fa-icon
      ></a>
      <a mat-icon-button class="btn-mail" href="mailto:"
        ><fa-icon [icon]="faCoffee"></fa-icon
      ></a>
    </div>
  </div>
  <div>
    <p>© Copyright 2018 Ristorante Con Fusion</p>
  </div>
</div>
